app = "casa-chindea"
primary_region = "ams"

[http_service]
  internal_port = 8090
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  internal_port = 8090
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  memory = "2gb"
  cpu_kind = "shared"
  cpus = 2
